server:
  port: 8888
spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vladisvit/config_server
          default-label: master  # or master, depending on your repo